package com.ncu.table.ivalue;

import java.util.Date;

public interface IHouseValue{
  public final static String S_HouseId = "HOUSE_ID";
  public final static String S_LandlordId = "LANDLORD_ID";
  public final static String S_Province = "PROVINCE";
  public final static String S_City = "CITY";
  public final static String S_DetailAddress = "DETAIL_ADDRESS";
  public final static String S_Room = "ROOM";
  public final static String S_Hall = "HALL";
  public final static String S_Toilet = "TOILET";
  public final static String S_HouseName = "HOUSE_NAME";
  public final static String S_HouseType = "HOUSE_TYPE";
  public final static String S_RentType = "RENT_TYPE";
  public final static String S_HouseArea = "HOUSE_AREA";
  public final static String S_Information = "INFORMATION";
  public final static String S_DepositType = "DEPOSIT_TYPE";
  public final static String S_Money = "MONEY";
  public final static String S_CreateDate = "CREATE_DATE";
  public final static String S_ModifyDate = "MODIFY_DATE";
  public final static String S_DelFlag = "DEL_FLAG";
  public void setHouseId(Long value);
  public void setLandlordId(Long value);
  public void setProvince(String value);
  public void setCity(String value);
  public void setDetailAddress(String value);
  public void setRoom(Long value);
  public void setHall(Long value);
  public void setToilet(Long value);
  public void setHouseName(String value);
  public void setHouseType(String value);
  public void setRentType(String value);
  public void setHouseArea(Long value);
  public void setInformation(String value);
  public void setDepositType(String value);
  public void setMoney(Long value);
  public void setCreateDate(Date value);
  public void setModifyDate(Date value);
  public void setDelFlag(Long value);
  public Long getHouseId();
  public Long getLandlordId();
  public String getProvince();
  public String getCity();
  public String getDetailAddress();
  public Long getRoom();
  public Long getHall();
  public Long getToilet();
  public String getHouseName();
  public String getHouseType();
  public String getRentType();
  public Long getHouseArea();
  public String getInformation();
  public String getDepositType();
  public Long getMoney();
  public Date getCreateDate();
  public Date getModifyDate();
  public Long getDelFlag();
}