document.write("<script src=\"js/jquery-3.1.1.min.js\"></script>");
document.write("<script src=\"js/bootstrap.min.js\"></script>");
document.write("<script src=\"js/valid.js\"></script>");
document.write("<script src=\"js/sweet-alert.min.js\"></script>");
document.write("<script src=\"js/json2.js\"></script>");
document.write("<script src=\"js/jquery.qtip.min.js\"></script>");
document.write("<script src=\"js/util.js\"></script>");
document.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/sweet-alert.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.qtip.min.css\">");