document.write("<script src=\"js/jquery-3.1.1.min.js\"></script>");
document.write("<script src=\"js/bootstrap.min.js\"></script>");
document.write("<script src=\"js/valid.js\"></script>");
document.write("<script src=\"js/json2.js\"></script>");
document.write("<script src=\"js/jquery.qtip.min.js\"></script>");
document.write("<script src=\"js/util.js\"></script>");
document.write("<script src=\"js/jquery.cookie.js\"></script>");
document.write("<script src=\"layer/js/layer.js\"></script>");
document.write("<script src=\"cityPicker/js/cityData.js\"></script>");
document.write("<script src=\"cityPicker/js/cityPicker.js\"></script>");
document.write("<script src=\"js/webuploader.js\"></script>");
document.write("<script src=\"js/upload.js\"></script>");
document.write("<script src=\"js/jBootstrapPage.js\"></script>");
document.write("<script src=\"jQueryMagnifier/js/magnifier.js\"></script>");

document.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.qtip.min.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/base.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"layer/css/layer.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"cityPicker/css/cityPicker.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/webuploader.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/upload.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jBootsrapPage.css\">");
document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jQueryMagnifier/css/magnifier.css\">");